### ISSUE TITLE
Invalid ELF header

### ISSUE THREAD

**Issue by melihmucuk** [crispymtn/crispyfi#11]
It's running on 64 bit Ubuntu14.04, I create folder in root and copy/paste all of the source. I changed config.js and copy/paste my spotify_appkey.key into the this folder. Then run "npm install" command inside the folder, everything installed. Then run "npm start" and I get this error (I also tried with "node index" command):

/root/slackify/node_modules/coffee-script/lib/coffee-script/register.js:45
      Module._extensions[extension](this, filename);
                                   ^
Error: /root/slackify/lib/spotify/mac/nodespotify.node: invalid ELF header
  at Error (native)
  at Module.load (/root/slackify/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Object.<anonymous> (/root/slackify/lib/spotify/mac/spotify.js:1:78)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (/root/slackify/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at module.exports (/root/slackify/lib/slack_interface/index.coffee:14:15)
  at Object.<anonymous> (/root/slackify/index.js:11:60)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Function.Module.runMain (module.js:501:10)
  at startup (node.js:129:16)
  at node.js:814:3

**Comment by dkoch** [comment]
You need a compatible binary version of [node-spotify](https://github.com/FrontierPsychiatrist/node-spotify). This project only comes bundled with a version for Mac and one for the Raspberry Pi.

You can try downloading [this](http://www.node-spotify.com/builds/0.7.0/node-spotify-0.7.0-linux.zip) and use it to overwrite the contents of `lib/spotify/mac/` (the `mac` dir is automatically chosen when it's not running on a Pi as this was developed on a Mac).

**Comment by melihmucuk** [comment]
Now I'm getting this error:

/root/slack/node_modules/coffee-script/lib/coffee-script/register.js:45
      Module._extensions[extension](this, filename);
                                   ^
Error: libspotify.so.12: cannot open shared object file: No such file or directory
  at Error (native)
  at Module.load (/root/slack/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Object.<anonymous> (/root/slack/lib/spotify/mac/spotify.js:1:78)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (/root/slack/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at module.exports (/root/slack/lib/slack_interface/index.coffee:14:15)
  at Object.<anonymous> (/root/slack/index.js:11:60)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Function.Module.runMain (module.js:501:10)
  at startup (node.js:129:16)
  at node.js:814:3

**Comment by timbofield** [comment]
Bump, same issue before and after fix.

**Comment by dkoch** [comment]
As the error message states, you need to install libspotify which is provided by Spotify themselves [here](https://developer.spotify.com/technologies/libspotify/). As for actually installing it, [this](https://docs.mopidy.com/en/v0.7.3/installation/libspotify/) seems to be as good an instruction as any.

**Comment by timbofield** [comment]
Thanks you that fixed it
