### ISSUE TITLE
Error: libspotify.so.12: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by doppenhe** [crispymtn/crispyfi#16]
Installed libspotify , node etc all on rasberrypi. Cannot get it past this error.

node index
/home/pi/crispyfi/config.json
/home/pi/crispyfi/node_modules/apiserver/index.js
/home/pi/crispyfi/node_modules/apiserver/lib/apiserver.js
/home/pi/crispyfi/node_modules/apiserver/node_modules/qs/index.js
/home/pi/crispyfi/node_modules/apiserver/node_modules/qs/lib/querystring.js
/home/pi/crispyfi/node_modules/apiserver/lib/middleware/index.js
/home/pi/crispyfi/node_modules/apiserver/node_modules/json-transport/index.js
/home/pi/crispyfi/node_modules/apiserver/node_modules/json-transport/lib/json-transport.js
/home/pi/crispyfi/node_modules/apiserver/lib/middleware/httpauth.js
/home/pi/crispyfi/node_modules/apiserver/lib/middleware/payload-parser.js
/home/pi/crispyfi/node_modules/apiserver/node_modules/bufferjoiner/index.js
/home/pi/crispyfi/node_modules/apiserver/node_modules/bufferjoiner/lib/bufferjoiner.js
/home/pi/crispyfi/node_modules/apiserver/lib/middleware/multipart-parser.js
/home/pi/crispyfi/node_modules/apiserver/node_modules/formidable/lib/index.js
/home/pi/crispyfi/node_modules/apiserver/node_modules/formidable/lib/incoming_form.js
/home/pi/crispyfi/node_modules/apiserver/node_modules/formidable/lib/file.js
/home/pi/crispyfi/node_modules/apiserver/node_modules/formidable/lib/multipart_parser.js
/home/pi/crispyfi/node_modules/apiserver/node_modules/formidable/lib/querystring_parser.js
/home/pi/crispyfi/node_modules/apiserver/node_modules/formidable/lib/octet_parser.js
/home/pi/crispyfi/node_modules/apiserver/node_modules/formidable/lib/json_parser.js
/home/pi/crispyfi/node_modules/apiserver/node_modules/apiserver-router/index.js
/home/pi/crispyfi/node_modules/apiserver/node_modules/apiserver-router/lib/router.js
/home/pi/crispyfi/node_modules/apiserver/node_modules/apiserver-router/node_modules/xregexp/xregexp-all.js
/home/pi/crispyfi/node_modules/apiserver/node_modules/fnchain/index.js
/home/pi/crispyfi/node_modules/apiserver/node_modules/fnchain/lib/fnchain.js
/home/pi/crispyfi/node_modules/apiserver/package.json
/home/pi/crispyfi/lib/slack_interface/index.coffee
/home/pi/crispyfi/lib/spotify/pi/spotify.js
/home/pi/crispyfi/lib/spotify/pi/nodespotify.node

/home/pi/crispyfi/node_modules/coffee-script/lib/coffee-script/register.js:46
      Module._extensions[extension](this, filename);
                                   ^
Error: libspotify.so.12: cannot open shared object file: No such file or directory
  at Module.load (/home/pi/crispyfi/node_modules/coffee-script/lib/coffee-script/register.js:46:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/home/pi/crispyfi/lib/spotify/pi/spotify.js:1:78)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/home/pi/crispyfi/node_modules/coffee-script/lib/coffee-script/register.js:46:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at module.exports (/home/pi/crispyfi/lib/slack_interface/index.coffee:12:15)
  at Object.<anonymous> (/home/pi/crispyfi/index.js:11:60)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:935:3

**Comment by leonaves** [comment]
Hope this isn't too late but chances are you have the wrong version of libspotify, if you're on the pi, make sure you're using the libspotify sdk for eabi-armv6hf

**Comment by doppenhe** [comment]
ended up with PiMusicBox and reverse engineering their websockets from slack. 

Thanks though!

**Comment by theomarkkuspaul** [comment]
Currently experiencing same issues as above. However, the Libspotify / CocoaSpotify Libraries have been removed from SpotifyAPI. Are there any work arounds to connect my Pi to Spotify/Slack without these dependencies?
